stages:
  - build
  - deploy

mkdocs:
  stage: build
  image:
    name: squidfunk/mkdocs-material:7.1.7
    entrypoint: [""]
  script:
    - mkdocs build
  artifacts:
    paths:
    - site
    expire_in: 2yrs

editorconfig:
  stage: build
  image: 
    name: odannyc/eclint
    entrypoint: [""]
  dependencies: [] # job can start immediately
  allow_failure: true
  script:
    - eclint check $(git ls-files)

ftp:
  stage: deploy
  image: ubuntu:focal
  script:
    - apt-get update && apt-get install -y lftp ca-certificates
    - lftp -e "set dns:order 'inet inet6';
               mirror -R site/ public/ ; quit"
           -u $FTP_USER,$FTP_PASS $FTP_HOST
  only:
    - master
  except:
    - tags
  environment:
    name: production
    url: https://roadmap.sch.bme.hu/
