site_name: schdesign roadmap
site_author: schdesign
site_description: >-
  A Simonyi Károly Szakkollégiumban működő schdesign öntevékeny kör
  szakmai anyagainak gyűjtőhelyéül szolgáló platform.

repo_name: schdesign/roadmap
repo_url: https://git.sch.bme.hu/schdesign/roadmap
edit_uri: ""

theme: 
  name: material
  custom_dir: docs/theme
  static_templates:
    - 404.html
  include_search_page: false
  search_index_only: true
  features:
     - navigation.instant
    #- navigation.sections
     - navigation.tabs
  language: hu
  palette:
    #scheme: preference # selects theme automatically using the user's preference in OS settings
    #scheme: slate # automatically selects dark theme no matter what OS settings are
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  icon:
  logo: img/schdesign_s_logo.svg
  favicon: img/favicon.png

extra_javascript: 
  - javascript/extra.js
extra_css: 
  - stylesheets/extra.css
  

# Plugins
plugins:
  - search
  - minify:
      minify_html: true

  # Extensions
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde


extra:
  social:
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/schonherzdesignstudio/
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/schdesign.hu/
    - icon: fontawesome/brands/gitlab
      link: https://git.sch.bme.hu/schdesign
    - icon: fontawesome/brands/behance
      link: https://www.behance.net/wearethesds/
    #- icon: fontawesome/brands/github
    #  link: https://github.com/squidfunk

nav:
  - Kezdőlap:
    - Kezdőlap: index.md
    - Markdown Alapok: alapok.md
    - Rólunk: rolunk.md
  - Web:
    - Web divízió: web/division.md
    - Első lépések: web/elso-lepesek.md
    - Workshopok: 
      - 2020/21/1 Todo: web/workshop/2020-21-1_todo-list.md
      - 2020/21/2 Kezdő: web/workshop/2020-21-2_web-1.md
      - 2020/21/2 Haladó: web/workshop/2020-21-2_web-2.md
    - Weboldal készítés az alapoktól:
      - 0. Bevezetés: web/tutorials/step-by-step/sbs_00_bevezeto.md
      - 1. HTML: web/tutorials/step-by-step/sbs_01_html.md
      - 2. CSS: web/tutorials/step-by-step/sbs_02_css.md
      - 3. JS: web/tutorials/step-by-step/sbs_03_js.md
      - 4. Hova tovább: web/tutorials/step-by-step/sbs_04_hova-tovabb.md
  - Grafika:
    - Grafika divízió: grafika/division.md
    - Hasznos oldalak: grafika/grafika-hasznos.md
  - 3D:
    - 3D divízió: 3d/division.md
    - Interfész - 1.: 3d/interfesz-1.md
    - Interfész - 2.: 3d/interfesz-2.md
    - Denoising: 3d/denoising.md
