site_name: schdesign roadmap
site_author: schdesign
site_description: >-
  A Simonyi Károly Szakkollégiumban működő schdesign öntevékeny kör
  szakmai anyagainak gyűjtőhelyéül szolgáló platform.

repo_name: schdesign/roadmap
repo_url: https://git.sch.bme.hu/schdesign/roadmap
edit_uri: ""

theme: 
  name: material
  custom_dir: docs/theme
  static_templates:
    - 404.html
  include_search_page: false
  search_index_only: true
  features:
    - tabs
  language: hu
  palette:
    scheme: preference
  font:
    text: Roboto
    code: Roboto Mono
  icon:
  logo: img/schdesign_s_logo.svg
  favicon: img/favicon.png

extra_javascript: 
  - javascript/extra.js
extra_css: 
  - stylesheets/extra.css
  

# Plugins
plugins:
  - search

  # Extensions
markdown_extensions:
  - smarty
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: schdesign
      repo: roadmap
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true


extra:
  social:
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/schonherzdesignstudio/
    - icon: fontawesome/brands/github
      link: https://github.com/squidfunk
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/schdesign.hu/
    - icon: fontawesome/brands/behance
      link: https://www.behance.net/wearethesds/

nav:
  - Kezdőlap: index.md
  - Markdown Alapok: alapok.md
  - Web:
    - Web divízió: web/web.md
    - Első lépések: web/elso-lepesek.md
    - Minden amit weboldal készítésről tudni akartál, de sosem merted megkérdezni:
      - 0. Bevezetés: web/tutorials/step-by-step/sbs_00_bevezeto.md
      - 1. HTML: web/tutorials/step-by-step/sbs_01_html.md
      - 2. CSS: web/tutorials/step-by-step/sbs_02_css.md
      - 3. JS: web/tutorials/step-by-step/sbs_03_js.md
      - 4. Kitekintés: web/tutorials/step-by-step/sbs_04_kitekinto.md
    - HTML: web/html.md
    - CSS: web/css.md
    - Javascript: web/js.md
  - Grafika:
    - Grafika divízió: grafika/grafika.md
    - Hasznos oldalak: grafika/grafika-hasznos.md
  - 3D:
    - 3D divízió: 3d/3d.md
    - Interfész - 1.: 3d/interfesz-1.md
    - Interfész - 2.: 3d/interfesz-2.md
    - Denoising: 3d/denoising.md
  - Rólunk: rolunk.md
